### ISSUE TITLE
Export History

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1698]
Appetite: 7 dev days

Description 
We want project collaborators to be able to export work order history from the history page for audit purposes. With the data storage policy/settings, users can configure their OpenFn account to wipe projects every 7 days or at a longer cadence depending on their data policy. While users might opt to the wipe data off every 7 days (for instance), there is no way for them to have a backup of the data via an export. This export feature will allow every collaborator on a project to be able to export work order history and related artifacts by clicking an export history button. 

How would this work?
An export history button on the history page will allow users to export a list of the history based on the current filtering criteria. When the button is pressed, a background process is activated to fetch all history and upload them to a GCP storage. When the upload is complete, a signed URL to the export is generated and an email is sent to the user who initiated it. 
In V1, we had a [GCP setup] (https://github.com/OpenFn/platform-app/tree/main/lib/open_fn/external_storage) that can be reused for this project.

When the export is complete, the user can via the list of exports from the export history page and download any export from the page directly or via the email that is sent to them. Export download links expire after 24 hours and the expiration status of the exports will show on the table as well.

The downloaded export is a zipped file (history_export_{{uuid of export}}.zip) that contains all work orders, run, data clips and logs matching the currently applied filter

What is included in an export?
Work Orders including runs, steps (via run_steps), logs, and I/O data clips
![Image](https://github.com/user-attachments/assets/382bfd13-b29e-4ed0-9aaa-9d52a990f88b)

Who can generate history exports in a project? 
All users with access to a project (editor, admin, owner, viewer) can create an export. When an export is generated we need to ensure that they can't delete the export from the table for audit purposes. 

Solution
- [ ] Spike storage backends with only cloud service (use v1 code heavily for GCP bucket) required for this bet.
- [ ] Add “cloud download” icon in top right of history page to “export by current query”.
- [ ] Implement confirmation modal.
- [ ] Add “downloads” page.
- [ ] Add links to exports (expire after 24 hours)
  - Will need to use the ExternalStorage module to request a URL
  - We need an authorized project files controller that returns either a signed url or sends the file to the requester (local storage mode)
- [ ] Send email when export is complete

V1 Stuff that can be reused
[ExportController](https://github.com/OpenFn/platform-app/blob/main/lib/open_fn_web/controllers/export_controller.ex)
[ArchiveService](https://github.com/OpenFn/platform-app/blob/main/lib/open_fn/services/archive_service.ex),
[DataExport](https://github.com/OpenFn/platform-app/tree/main/lib/open_fn/external_storage)

Issues:

- [ ] #1759 
- [ ] #1763 
- [ ] #1765 
- [ ] #1766 
- [ ] #1767 
- [ ] #1769 

Design here: https://www.figma.com/design/4hGWdO4sajnjcOwE81j8BK/App-(new)?node-id=4879-1193&t=Gg4oWU4YXgWVjkdy-0

#### How to export
<img width="403" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/7c0eb4a4-8124-4aea-b11f-c93e09e2b12f">

<img width="644" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/009bd006-e177-480a-8fca-8b650b0da81b">

### How to View Exports

<img width="1674" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/2822cf0b-65d9-4523-8b5e-49fe505f2e80">

### The Email

![Image](https://github.com/OpenFn/Lightning/assets/8732845/3812331d-86a3-45e9-acd0-78bdad58f7ee)

### Notes

- This epic does _not_ cover the automatic archive service. This feature will be rolled out later, and considered as the export feature it built. The archive service runs an automatic export on all history that is _about to expire_ for paid plans with 12 month data storage. It moves history off the platform and to cloud storage _before_ that history is purged from OpenFn removed.
