### ISSUE TITLE
Allow (normal) users to create new projects with limiter

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1700]
### Business Justification
- We think that users will want to create a new project with a subscription rather than “updating” their initial dirty demo project.
- More revenue
- Implementing this allows us to fix the navigation experience on Thunderbolt and make it seamless for users to switch between project, user, and billing scopes. 

### Design: 
https://www.figma.com/design/4hGWdO4sajnjcOwE81j8BK/App-(new)?node-id=4679-570&t=wyW6Zg0T2S9ClNT1-0

### Job to be done (https://github.com/OpenFn/thunderbolt/issues/29)
We are implementing a new projects dashboard, which will be the new landing screen for users when they login to app.openfn.org. Users will be able to see the list of projects they have access to and can create a new project if required. 

Lightning users are expected to ONLY provide the project name and description to create a new project while Thunderbolt users are expected to select a billing account and proceed to pick a plan for their project. The pick a Plan page is a 90% pixel-to-pixel match of the current modify subscription page that allows every new user to select a subscription, add additional runs, and choose a payment method for their project subscription. 
 
- [x] Create a new project
- [x] Implement a projects' dashboard that allows users to view all projects that I have access to in a table view
- [x] Ensure the user’s billing account has an associated payment method
- [x] Create subscription for the user based on the selected plan, and billing term and create a charge on the payment method.
- [x] Add menu items to the left menu to allow users to switch between project and billing scope seamlessly. 

We are branching off Taylor's work on new headers [here](https://github.com/OpenFn/lightning/pull/2299). 

### Budget: 
- Appetite: 5 Days
- Staff: 2 Engineers

### Notes
Here are other related issues
- [x] #1991 
- We should also use this opportunity to deliver on enabling users to delete projects and how project deletion will [impact subscriptions](https://github.com/OpenFn/thunderbolt/issues/146).

**Comment by taylordowns2000** [comment]
note that we shouldn't call the projects list view a "dashboard". it's a list view.
