### ISSUE TITLE
Better Version Control

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1815]
This epic covers our next iteration of version control via Github

- [x] https://github.com/OpenFn/lightning/issues/1894
- [x] #1895 
- [x] https://github.com/OpenFn/lightning/issues/1811
- [x] https://github.com/OpenFn/lightning/issues/1812

Maybe later: 

- [x] https://github.com/OpenFn/lightning/issues/1813
- [x] https://github.com/OpenFn/lightning/issues/1649
- [x] https://github.com/OpenFn/lightning/issues/1807
