### ISSUE TITLE
Implement Generic Oauth 2.0

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#1900]
Implement a generic interface and feature for users to set up Oauth 2.0 authentication across their projects on Lightning. A generic Oauth will allow users to add  and share multiple clients across projects and subsequently adding credentials on their clients.

TODO:
- [x] #1919
- [x] #1920
- [x] #1921
- [x] #1922
- [x] #1923
- [x] #1924

![Image](https://github.com/OpenFn/lightning/assets/5230530/5e257db7-7061-4e25-87e1-f02526779a4d)

Requires Design: 
- [x] Yes
- [ ] No 

Design Ready?
- [x] Yes https://www.figma.com/file/2Uvr2jOaQh6rQNR1cHlLKM/App?type=design&node-id=2249-4048&mode=design&t=oHympJZmrVd3Cvn0-0
- [ ] No
 
Validation: 
- [ ] Successfully create a client
- [ ] Use a client to create a credential
- [ ] Create a client and do not share with any other project -- the client should only be accessible in the project where it's created.
- [ ] Create a client and share it within a number of projects, switch to the project to see if the client is listed on the credentials page and can be used to create a new credential.
- [ ] Only admins and superusers should be able to share clients across projects.

Take note of: https://github.com/OpenFn/lightning/issues/1693
Related : https://github.com/OpenFn/lightning/issues/664
