### ISSUE TITLE
Improve debugging experience

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2062]
We want to make debugging jobs/runs easier and better for users by enabling a number of features on the editor and inspector interface. 

TODO: 
- [ ] Allow users to be able to download input/output data clips and logs
- [ ] Allow users to be able to search logs, input/output data clips from the inspector/editor
- [ ] Allow users to be able to copy logs and data clips by clicking on a clipboard icon
