### ISSUE TITLE
ATNA audit trail refactor/expand functionality

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#271]
- [x] remove cascades
- [x] drop FK constraint on `row`
- [x] drop FK constraint on `actor`
- [x] ensure there's an index on the `actor`
- [x] rename `row` relationship to `item`
- [x] ensure there's an index on the `item`
- [x] add `item_type` column
- [x] change `metadata` to `changes` jsonb
- [x] keep `{ before: ..., after: ...}` in `changes`
- [x] change `credentials_audit` to `audit_events` -> each separate audit MODEL is its own module, with its own structs, handling, etc., but they use the same DB schema: `audit_events`

**Comment by taylordowns2000** [comment]
- drop FK constraint on `item_id`
- drop FK constraint on `author_id`
- ensure there's an index on the `item_id`
- ensure there's an index on the `author_id`
- add `item_name` column
- change `metadata` to `changes` jsonb
-

**Comment by taylordowns2000** [comment]
On the issue of whether "sharing credential access to a project" should generate an audit trail entry for `project_credentials` (create) or just `credentials` (update)... we've decided that the purpose of the audit trail (in the spirit of ATNA) is to document real user interaction with the application, not to generate a row history for the DB...

rather, if a user changes the name of a credential and grants it access to the "newthing" project, we should have an event `credential_access_updated` record linked to event_id `123`
```
{
  "after": {
    "projects": ["tay", "stu", "newthing"]
  },
  "before": {
    "projects": ["tay", "stu"]
  }
}
```
AND a `credential_updated` record linked to event_id `123`
```
{
  "after": {
    "name": "new name"
  },
  "before": {
    "name": "old name"
  }
}
```

**Comment by amberrignell** [comment]
Once we have updated the audit module, replace the delete SQL query.

**Comment by taylordowns2000** [comment]
@wanecode , @stuartc , FYI - slight changes were made to the `credentials_audit` table in order to track credential delete events, but we did _not_ start on this bigger audit_event refactor. Let's keep this epic in mind (@amberrignell !) for the next time we add or change audit trail functionality.

**Comment by taylordowns2000** [comment]
todo:
1. project_credential and project changes
2. decide what to do about actor_id or email
3. decide if there's a better way to get "credentials" (or any item_type) into the event
