### ISSUE TITLE
Create a WorkOrder

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#358]
Provide a new module (name pending) that provides a function to handle safely creating a webhook and a cron workorder.

> _safely_ implies that a transaction may be required, as any failure should not result in any orphaned records.

This new module will very likely replace parts of the `Invocation` context.

![image.png](https://images.zenhubusercontent.com/55ba74804f7a08fbb7f40152/9388d558-16b6-4518-901d-6825f4014047)

## TODOs

- [x] Provide replacement functions for the Pipeline that will handle creating new/next runs on success/failure of prior runs.
- [x] Remove `event_id` from Runs (:point_up: might require above to be done)
- [x] Create convenience function/s for `InvocationReasons`  
  that takes a trigger and a dataclip and given the trigger type, build a reason with either a webhook or cron type.
  `InvocationReasons.build(trigger, dataclip) => Ecto.Changeset...`
- [x] Remove `project_id` from Run table and associated schema.
- [x] Change WebhookController and Cron Scheduler to use (new) functions from the `WorkOrderService`
