### ISSUE TITLE
Import project.yaml

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#574]
Write a function which, given a project.yaml file with the format defined in [projects_as_code](https://github.com/OpenFn/projects-as-code), creates a project with the given workflows and jobs. 

Out of scope: http or cli interface

The function should take a map, create the resources and return the models that it makes. If you call the function on it's own, no users get created. (when we add the cli, the user that is calling the function will be added as the project owner). 

### User acceptance criteria: 
- [ ] Given a data structure with a workflow A and workflow B, when I call the function xxx with it, I can see that project on the admin settings>projects page
- [ ] When I add myself as a member of that project, I can see 2 workflows on my workflows index page
- [ ] The function should return the models that it makes. 
- [ ] If the project already exists, throw an error. 

(notes for other issues)
1. Fix export project in Lightning 
2. Write function that creates a project based on a data structure (this issue)
3. Deploy through the CLI - add a command to the CLI which calls a lightning endpoint and deploys a new project from a project.yaml file

**Comment by amberrignell** [comment]
The RDP (reduced deployment payload) for a credential should look like the model for credentials. 
Assume that you are receiving json that matches our models, and then the next step will be to figure out the CLI side of things and how we can get from a yaml to the correct RDP.

**Comment by amberrignell** [comment]
Context: One to many relationship between credentials and projects. 
In the project there is a credentials association with 'true' for project_credentials
-> either access through project credentials or the project association 

currently trying to: get all the models at once by adding task associations on the data struct
Problem: generating a credential ID before you add it to the project (ie: before the project gets saved)
Solution: use multi to create dynamic database transactions

note: make sure that we return a tuple with error and a map of changesets (so that the API can down the line return proper error messages)

Credential validation: currently just check that the credential has a name, body and schema
TODO [Amber & Stu to add issue]: different credentials have different validation strategies (currently handled in forms).
