### ISSUE TITLE
User roles and permissions 

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#594]
Review current authorization implementation to follow best practice and avoid hard-coding roles. 
https://owasp-top-10-proactive-controls-2018.readthedocs.io/en/latest/c7-enforce-access-controls.html#don-t-hardcode-roles

Currently, access controls happen on user roles in separate policy files - this pattern makes it difficult to see every single action a user with a given role can perform. 

```
  # Super users can do anything
  def authorize(_action, %User{role: :superuser}, _params), do: true

  # Regular users can't access user management page
  def authorize(action, %User{role: :user} = _user, _params)
      when action in ~w[index show]a,
      do: false

  # Default blacklist
  def authorize(_action, _user, _params), do: false
end
```

Expected:
- [x] There is one place in the app where I can see all of the permissions granted for each role (or at least a very easy way of auditing it)
- [x] All functions / possible actions in Lightning have an authorize statement around them

**Define permissions for viewer, editor and admin of a project_user:** 
Note: below list is just indication / example, we need to think about this carefully
- viewer: [view_workflow, view_project_members, view_credentials_list, view_runs] <- run a job ?
- editor: [view_workflow, edit_workflow, view_project_members, view_credentials_list, view_runs, run_job]
- admin: [view_workflow, edit_workflow, delete_workflow, add_member, remove_member, run_job, view_credentials_list, view_runs]

See roles and permissions doc for context: https://docs.google.com/spreadsheets/d/1mlWjlvVdhupI3Ph0msf9nE2K7Uoe-qklOj81cG0N19c/edit?usp=drive_open&ouid=117811280250615103178 

Acceptance criteria: 
- [x] Given a project_user with role viewer, when they open the job editor, the save button is disabled.
