### ISSUE TITLE
Out of Process Worker Queue

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#676]
In order to support out-of-process workers, we need to provide a simple and
reliable datastore containing all 'to be executed' Jobs.

Taking inspiration from Oban (and others), we can use Postgres and it's 
`FOR UPDATE SKIP LOCKED` clause when allocating[^1] work.

There are two distinct reasons why we can't use Oban in this situation:

1. The work is not performed in Elixir, thus making a large portion of the 
facilities that Oban offers unsuitable.
2. We want to be able to control the criteria for the next job to be executed.

Determining what Job is to be processed next benefits from custom queries. 

Where Oban and others provide the ability to set concurrency for a queue and
priority for a task; 

- in our new design we don't control the concurrency of the workers  
  (They will be dynamically scaled up and down depending on demand).
- we want to control the concurrency of a Job scoped by it's workflow concurrency and project concurrency.

By controlling the queue at the allocation query, we get the opportunity to exclude jobs that are at their specified maximum concurrency (by project and/or workflow settings). This replaces the red/green mechanism in the original implementation.

We are leaning on Postgres to act as the 'singleton' here, with it's transactional features we can ensure 'at most once' execution; and I've seen benchmarks that make me feel very comfortable with the performance roadmap.

![image](https://user-images.githubusercontent.com/144796/223128596-b80db40e-217e-4f1d-ade5-32240fea6d51.png)

![image](https://user-images.githubusercontent.com/144796/223130741-56c48c98-5f2b-473f-ad46-f9e900a45e43.png)

## TODO

- [ ] Decide on the columns for a `RunQueue` table.
- [ ] Plan out the API interfaces for enqueueing and updating an entry on the `RunQueue`.
- [ ] The design _must_ accommodate for custom query module integration;  
      this is crucial for adapting the behaviour for different situations.

[^1]: Allocate work means to mark a job as 'taken' for processing, preventing
it from being picked up by some other worker or process.

### Implementation notes

This issue does not include integration with the Pipeline, the UI or provide any guidelines on the interfaces provided to workers.

This requires follow up planning.

**Comment by taylordowns2000** [comment]
@stuartc , similar question on this one.... has this issue actually been subsumed by #973 ?

**Comment by NickOpenFn** [comment]
Closed by #983
