### ISSUE TITLE
Validation & Logic for Triggers

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#863]
A trigger is a special "start event" node in a workflow graph—it's represented with a circle ⭕️— that will _**automatically**_ produce a workorder for that workflow based on either a `cron` schedule or the receipt of a `webhook` request.

Spec:
- [ ] Triggers themselves can be disabled or enabled.
- [ ] You can delete a webhook trigger or delete a cron trigger.
- [ ] You cannot change a webhook trigger to a cron trigger.
- [ ] You do not need a trigger for a workflow. (A workflow without a trigger can only be run manually, but might be useful for intentional, supervised batch processing.)
- [ ] You cannot have more than one `cron` trigger for a workflow.
- [ ] You cannot have more than one `webhook` trigger for a workflow.
- [ ] Even if you have both a cron trigger and a webhook trigger for a workflow, they both must point to the same job. (Otherwise, they would be different workflows.)
- [ ] A trigger cannot have more than one `edge`.

**Comment by NickOpenFn** [comment]
@taylordowns2000 
I think I might be a little daft here! The validation in this case would be what exactly? As far as I can see, all the items above are handled via the UI already, with the exception of number `3`?

**Comment by taylordowns2000** [comment]
Well yes and no :-) 

Validation is not the right word for the title of this issue. (And the issue is actually an epic!) There's no way to create or delete triggers, no way to enable or disable them, and we need to prevent users from changing their type. Lots of stuff in here that needs drawing in Figma—very little actual Elixir-based "validation rules" on trigger-save.

**Comment by NickOpenFn** [comment]
Deleting this as the items are too self contained to be a Epic really...
